# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    match(type: "adhoc", force_for_new_devices: true)
    match(type: "development", force_for_new_devices: true)
    increment_build_number(xcodeproj: "project3.xcodeproj")
    increment_version_number(
      bump_type: "patch" # Automatically increment minor version number
    )
    sync_code_signing(type: "appstore")
    build_app(workspace: "project3.xcworkspace", scheme: "project3")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end